Dev gradient
fyp21011/PlasticineLab pull request #24
Opened 2022-02-14 07:58 UTC by EE-LiuYunhao

# Gradient Backpropagation

Optimize the bridge between the robots' forward kinematics and the primitives' forward kinematics, and modify the gradient backpropagation accordingly. 

## Detailed modifications

## Tests

### Unit tests
All passed
<img width="316" alt="image" src="https://user-images.githubusercontent.com/43565614/149311476-06e46cf2-4002-412f-9513-ff417616d9a8.png">

### Functional tests
Passed. _(Video omitted)_

2022-02-18 16:52 UTC, shwnyao requested changes

2022-02-18 16:52 UTC, shwnyao commented on plb/engine/mpm_simulator.py
> +        self.fpc = free_primitives_controller if free_primitives_controller != None \
fpc 是指原來的 primitive嗎 看起來可以同時有多種controller?

2022-02-18 16:52 UTC, shwnyao commented on plb/engine/mpm_simulator.py
> +        self.rc.forward_kinematics.grad(s)
fpc和rc之間是不能用polymorphism 去簡化的嗎？

2022-02-18 16:52 UTC, shwnyao commented on plb/engine/mpm_simulator.py
> +            self.fpc.set_action(start//self.substeps, self.substeps,
@EE-LiuYunhao 這一段會導致沒有robot時action輸出None #25

2022-02-19 04:19 UTC, EE-LiuYunhao commented on plb/engine/mpm_simulator.py
> +            self.fpc.set_action(start//self.substeps, self.substeps,
Okay will check and resolve it.

2022-02-20 14:33 UTC, EE-LiuYunhao commented
@shwnyao Robot在act/act grad里面返回None然后被concatenate的问题应该解决了。你检查一下？

2022-02-20 15:03 UTC, shwnyao commented
@EE-LiuYunhao I tried the following command and this happened. It runs nnv2.
`python3 -m plb.algorithms.tune` 
```
Traceback (most recent call last):
  File "/root/shwnyao/PlasticineLab/plb/optimizer/solver_torch_nnv2.py", line 73, in train
    obs, reward, done, loss_info = self.env.step(action)
  File "/usr/local/lib/python3.6/dist-packages/gym/wrappers/time_limit.py", line 16, in step
    observation, reward, done, info = self.env.step(action)
  File "/root/shwnyao/PlasticineLab/plb/envs/env.py", line 44, in step
    self.taichi_env.step(action)
  File "/root/shwnyao/PlasticineLab/plb/engine/taichi_env.py", line 108, in step
    self.simulator.step(is_copy=self._is_copy, action=action)
  File "/root/shwnyao/PlasticineLab/plb/engine/mpm_simulator.py", line 469, in step
    self.substep(s)
  File "/usr/local/lib/python3.6/dist-packages/taichi/lang/__init__.py", line 861, in decorated
    func(*args, **kwargs)
  File "/root/shwnyao/PlasticineLab/plb/engine/mpm_simulator.py", line 321, in substep
    self.fpc.forward_kinematics(s)
AttributeError: 'Primitives' object has no attribute 'forward_kinematics'
```

2022-02-21 02:27 UTC, EE-LiuYunhao commented
@shwnyao This is my fault. I will fix it immediately.

2022-02-21 05:11 UTC, EE-LiuYunhao commented
@shwnyao The bug should be solved now. Could you please verify it?

2022-02-25 10:57 UTC, shwnyao commented
#25 has been solved.
LGTM

2022-02-25 10:57 UTC, shwnyao approved these changes

2022-02-25 10:58 UTC, merged